-- New design: expand core set to 16 peers and 8 transactions; refresh methodology.

-- Brunel leaves the core peer set (kept as a non-core reference row).
update public.comparable_companies set is_main = false where id = 12444477;

-- Three new core peers (Hitechpros, Korn Ferry, Insight Global).
insert into public.comparable_companies (id,name,description,country,country_code,flag,website,employees,ownership,revenue_musd,revenue_cagr_3yr,tev,ebitda_musd,ebitda_pct,ev_sales,ev_ebitda,ev_ebit,is_main,sort_order) values
(6824987,'Hitechpros','HiTechPros is an IT staffing platform that connects IT professionals with businesses, offering a range of services including staffing solutions, training, and consulting. The company serves a diverse clientele, including freelancers, training centers, and software publishers, facilitating access to numerous opportunities in the IT sector. HiTechPros operates a digital platform that enhances collaboration and sourcing in the IT community.','France','FR','🇫🇷','https://hitechpros.com',26,'Public',30.39676584,-0.009467,28.4209760604,2.3246675844,0.076477,0.935,12.2258,13.1338,true,14),
(90449,'Korn Ferry','Korn Ferry is a consulting firm specializing in organizational consulting services. They offer a range of solutions including talent acquisition, leadership development, and organizational strategy to help businesses and organizations enhance their performance and manage talent effectively. Their clients span various industries, seeking to navigate complex challenges and drive growth.','United States (USA)','US','🇺🇸','https://kornferry.com',21042,'Public',2761.086,0.014618,NULL,445.562,0.161372,0.9981,6.185,NULL,true,15),
(1304653,'Insight Global','Insight Global is a staffing agency and consulting firm that specializes in providing staffing and professional services across various industries. They assist businesses in finding qualified talent and offer solutions to improve operational efficiency. Their services include staffing, recruitment process outsourcing, and culture consulting, catering primarily to business clients.','United States (USA)','US','🇺🇸','https://insightglobal.com',19346,'Public',8247.18,-0.075322,NULL,416.985,0.050561,0.4601,9.099,NULL,true,16)
on conflict (id) do update set is_main=excluded.is_main, sort_order=excluded.sort_order, ev_sales=excluded.ev_sales, ev_ebitda=excluded.ev_ebitda;

-- Two new core transactions (PERBILITY, PandoLogic).
insert into public.precedent_transactions (target_name,buyer,country,deal_date,deal_year,segment,deal_size_usdm,valuation_usdm,ev_sales,ev_ebitda,ev_ebit,implied_revenue_musd,implied_ebitda_musd,relevance_note,relevance_stars,url,is_main,sort_order) values
('PERBILITY GmbH','Rivean Capital ← Main Capital','🇩🇪 DE','2024-10-01',2024,'HR SaaS / HRIS',110,NULL,3.3,10.4,9.9,33.3,10.6,'German HRIS/HR SaaS, 147 employees, DACH-focused PE LBO — strongest German comp with full multiples',2,'https://www.perbility.de',true,6),
('PandoLogic','Veritone ← Edison Partners','🇺🇸 US','2021-07-01',2021,'AI recruitment marketing',150,NULL,3.0,6.0,NULL,50.0,25.0,'AI-powered recruitment marketing platform — directly aligned with Michelscom''s tech-enabled positioning',2,'https://www.pandologic.com',true,7);

-- Methodology now reflects 16 peers / 8 transactions.
update public.valuation_assumptions set methodology = 'Indicative Enterprise Value derived by applying observed EV/EBITDA or EV/Sales multiples — from a screen of 16 listed recruitment & HR-services peers and 8 precedent transactions — to Michelscom''s FY2026E EBITDA (€2.6m) or revenue (€7.0m), depending on the selected multiple. Scenarios are defined as: Low = lower quartile, Median & Average = base case, Upside = midpoint of upper quartile and maximum, Max = highest observed multiple. An optional size adjustment discounts the multiples of size-outlier comps only — those whose EBITDA falls outside roughly one-third to three times Michelscom''s — to better reflect the target''s scale; peers of comparable size are left unadjusted. Quartiles are computed on the respective (adjusted) multiple sets; the blended figure equals the simple average of the two methods unless re-weighted. Figures are indicative, rounded to one decimal place, presented on a cash-free / debt-free Enterprise Value basis (no net-debt bridge to equity value), and do not constitute a fairness opinion or formal valuation. Peer multiples sourced from public FY2025 filings; transaction multiples from announced deal data. Prepared by atares for discussion purposes only.' where id = 1;
